server:
  servlet:
    session:
      cookie:
        secure: true

spring:
  session:
    store-type: none
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  security:
    oauth2:
      client:
        registration:
          eidp:
            client-secret: palette-secret
        provider:
          eidp:
            issuer-uri: http://localhost:8180/realms/palette

palette:
  application:
    environment: DEV
  security:
    cors:
      allowed-origins: https://localhost:3000
  session:
    store-type: memory
  eidp:
    logout-uri: http://localhost:8180/realms/palette/protocol/openid-connect/logout
    post-logout-redirect-uri: https://localhost:3000

logging:
  level:
    com.company.palette.bff: DEBUG
    org.springframework.security: DEBUG
