spring:
  session:
    store-type: none
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  security:
    oauth2:
      client:
        provider:
          eidp:
            authorization-uri: http://localhost:8080/dev/authorize
            token-uri: http://localhost:8080/dev/token
            jwk-set-uri: http://localhost:8080/dev/jwks
            user-info-uri: http://localhost:8080/dev/userinfo

palette:
  application:
    environment: DEV
  security:
    cors:
      allowed-origins: http://localhost:3000
  session:
    store-type: memory
  eidp:
    logout-uri: http://localhost:8080/dev/end-session
    post-logout-redirect-uri: http://localhost:3000

logging:
  level:
    com.company.palette.bff: DEBUG
    org.springframework.security: DEBUG
